name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Test
        run: |
          ls -ltr
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
          mvn clean package

      - name: Static Code Analysis
        env:
          SONAR_URL: "http://129.159.224.151:9000"
        run: |
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
          mvn sonar:sonar -Dsonar.login=${{ secrets.SONAR_AUTH_TOKEN }} -Dsonar.host.url=$SONAR_URL

      - name: Build and Push Docker Image
        env:
          DOCKER_IMAGE: "captainankush/ultimate-cicd:${{ github.run_number }}"
        run: |
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
          docker build -t $DOCKER_IMAGE .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push $DOCKER_IMAGE
          docker rmi $DOCKER_IMAGE

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: username/other-repo  # Replace with the username and repository name

          
      - name: Update Deployment File
        env:
          GIT_REPO_NAME: "springboot-actions"
          GIT_USER_NAME: "AnmolKushwaha"
          GIT_BRANCH_NAME: "argocd"
          REPLACE_TAG: ""
        run: |
          git branch 
          ls
          git config --local user.email "anmolkushwaha858@gmail.com"
          git config --local user.name "AnmolKushwaha"
          git remote set-url origin https://${{ secrets.G_TOKEN }}@github.com/$GIT_USER_NAME/$GIT_REPO_NAME
          git checkout $GIT_BRANCH_NAME
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests
          ls -ltr
          REPLACE_TAG= ":$(grep image deployment.yml | cut -d ":" -f3)"
          sed -i "s/$REPLACE_TAG/${{ github.run_number }}/g" deployment.yml
          git add deployment.yml
          git commit -m "Update deployment image to version {{ github.run_number }}"
          git push origin 
