name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Test
        run: |
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
          mvn clean package

      - name: Static Code Analysis
        env:
          SONAR_URL: "http://129.159.224.151:9000"
        run: |
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
          mvn sonar:sonar -Dsonar.login=${{ secrets.SONAR_AUTH_TOKEN }} -Dsonar.host.url=$SONAR_URL

      - name: Build and Push Docker Image
        env:
          DOCKER_IMAGE: "captainankush/ultimate-cicd:${{ github.run_number }}"
        run: |
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE
          docker rmi $DOCKER_IMAGE

      - name: Checkout Deployment Repository
        env:
          GIT_REPO_NAME: "springboot-actions"
          GIT_USER_NAME: "AnmolKushwaha"
          GIT_BRANCH_NAME: "argocd"
      
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GIT_USER_NAME }}/${{ env.GIT_REPO_NAME }}
          ref: ${{ env.GIT_BRANCH_NAME }}
          
      - name: Update Deployment File
        run: |
          git config --local user.email "anmolkushwaha858@gmail.com"
          git config --local user.name "{{ github.user }}"
          git remote set-url origin https://${{ secrets.G_TOKEN }}@github.com/${{ github.user }}/${{ github.repository }}
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests
          sed -i "s/$(grep image deployment.yml | cut -d ":" -f3)/${{ github.run_number }}/g" deployment.yml
          git add deployment.yml
          git commit -m "Update deployment image to version ${{ github.run_number }}"
          git push origin 
